websites:
  - name: "Instagram"
    base_url: "https://instagram.com/@{}"
    url_probe: ""
    errorType: "errorMsg" 
    errorMsg: "<title>Instagram</title>"

  - name: "Twitter/X"
    base_url: "https://twitter.com/{}"
    url_probe: ""
    errorType: "unknown"
    errorCode: 403

  - name: "GitHub"
    base_url: "https://github.com/{}"
    url_probe: ""
    errorType: "status_code" 
    errorCode: 404

  - name: "Reddit"
    base_url: "https://www.reddit.com/user/{}"
    url_probe: ""
    errorType: "errorMsg"
    errorMsg: "<title>Reddit - Dive into anything</title>"

  - name: "Facebook"
    base_url: "https://www.facebook.com/{}"
    url_probe: ""
    errorType: "errorMsg" 
    errorMsg: "<title>Facebook</title>"

  - name: "YouTube"
    base_url: "https://www.youtube.com/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "TikTok"
    base_url: "https://www.tiktok.com/@{}"
    url_probe: ""
    errorType: "errorMsg"
    errorMsg: ""

  - name: "About Me"
    base_url: "https://about.me/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Independent Academia"
    base_url: "https://independent.academia.edu/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404
  
  - name: "Airbit"
    base_url: "https://airbit.com/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Airliners"
    base_url: "https://www.airliners.net/user/{}/profile/photos"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Duolingo"
    base_url: "https://www.duolingo.com/profile/{}"
    url_probe: "https://www.duolingo.com/2017-06-30/users?username={}"
    errorType: "errorMsg"
    errorMsg: "{\"users\":[]}"

  - name: "Pinterest"
    base_url: "https://www.pinterest.com/{}"
    url_probe: ""
    errorType: "unknown"
    errorCode: 308

  - name: "VSCO"
    base_url: "https://vsco.co/{}"
    url_probe: ""
    errorType: "unknown"
    errorCode: 301

  - name: "Snapchat"
    base_url: "https://www.snapchat.com/add/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Threads"
    base_url: "https://www.threads.net/@{}"
    url_probe: ""
    errrorType: "errorMsg"
    errorMsg: "<title>Threads</title>"

  - name: "Tumblr"
    base_url: "https://www.tumblr.com/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Keybase"
    base_url: "https://keybase.io/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Wattpad"
    base_url: "https://www.wattpad.com/user/{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Mastodon Social"
    base_url: "https://mastodon.social/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "MSTDN Social"
    base_url: "https://mstdn.social/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Mas.to"
    base_url: "https://mas.to/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Mastodon World"
    base_url: "https://mastodon.world/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404
  - name: "Fosstodon"
    base_url: "https://fosstodon.org/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Hachyderm"
    base_url: "https://hachyderm.io/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Vivaldi Social"
    base_url: "https://social.vivaldi.net/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Techhub Social"
    base_url: "https://techhub.social/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404

  - name: "Techhub Social"
    base_url: "https://techhub.social/@{}"
    url_probe: ""
    errorType: "status_code"
    errorCode: 404